// ================================================================
// Design System — JS/TS Tokens
// Generated from design-tokens.json
//
// Usage in Framer code components:
// import { tokens } from "./design-tokens"
// background: tokens.colorSurfaceLightPage
// ================================================================

export const tokens = {
  // Color — Primitive
  colorPrimitiveWhiteandblack100: "#FDFDFD",
  colorPrimitiveWhiteandblack1200: "#242424",
  colorPrimitiveRedcoral100: "#FFF4F1",
  colorPrimitiveRedcoral200: "#FFE5DE",
  colorPrimitiveRedcoral300: "#FFCFC4",
  colorPrimitiveRedcoral400: "#FFB5A5",
  colorPrimitiveRedcoral500: "#FF9784",
  colorPrimitiveRedcoral600: "#F77461",
  colorPrimitiveRedcoral700: "#E54633",
  colorPrimitiveRedcoral800: "#C53A2B",
  colorPrimitiveRedcoral900: "#A83023",
  colorPrimitiveRedcoral1000: "#86251C",
  colorPrimitiveRedcoral1100: "#621A14",
  colorPrimitiveRedcoral1200: "#45120E",
  colorPrimitiveTeal100: "#F2FAFC",
  colorPrimitiveTeal200: "#E3F3F8",
  colorPrimitiveTeal300: "#CEE8F0",
  colorPrimitiveTeal400: "#AED9E6",
  colorPrimitiveTeal500: "#8CC8DB",
  colorPrimitiveTeal600: "#70B3CA",
  colorPrimitiveTeal700: "#5799AE",
  colorPrimitiveTeal800: "#448092",
  colorPrimitiveTeal900: "#336676",
  colorPrimitiveTeal1000: "#254D5A",
  colorPrimitiveTeal1100: "#19353E",
  colorPrimitiveTeal1200: "#102227",
  colorPrimitiveBluelavender100: "#EFF2FB",
  colorPrimitiveBluelavender200: "#CDD2EB",
  colorPrimitiveBluelavender300: "#BBC2E3",
  colorPrimitiveBluelavender400: "#A6ACC6",
  colorPrimitiveBluelavender500: "#8F99C2",
  colorPrimitiveBluelavender600: "#5D8DF7",
  colorPrimitiveBluelavender700: "#4C79D8",
  colorPrimitiveBluelavender800: "#3D63B7",
  colorPrimitiveBluelavender900: "#324F94",
  colorPrimitiveBluelavender1000: "#273D73",
  colorPrimitiveBluelavender1100: "#1C2B52",
  colorPrimitiveBluelavender1200: "#131D37",
  colorPrimitiveSuccessgreen100: "#F3F8F2",
  colorPrimitiveSuccessgreen200: "#E5F0E1",
  colorPrimitiveSuccessgreen300: "#D2E3CB",
  colorPrimitiveSuccessgreen400: "#B9D1AF",
  colorPrimitiveSuccessgreen500: "#9FBE93",
  colorPrimitiveSuccessgreen600: "#86AA78",
  colorPrimitiveSuccessgreen700: "#6D8E60",
  colorPrimitiveSuccessgreen800: "#58724C",
  colorPrimitiveSuccessgreen900: "#43583A",
  colorPrimitiveSuccessgreen1000: "#33432D",
  colorPrimitiveSuccessgreen1100: "#253021",
  colorPrimitiveSuccessgreen1200: "#182016",
  colorPrimitiveWarningamber100: "#FFF8EC",
  colorPrimitiveWarningamber200: "#FFF0D8",
  colorPrimitiveWarningamber300: "#FEE3B8",
  colorPrimitiveWarningamber400: "#FAD290",
  colorPrimitiveWarningamber500: "#EFC067",
  colorPrimitiveWarningamber600: "#DCA84E",
  colorPrimitiveWarningamber700: "#BE8C40",
  colorPrimitiveWarningamber800: "#9F7335",
  colorPrimitiveWarningamber900: "#7D5A29",
  colorPrimitiveWarningamber1000: "#604520",
  colorPrimitiveWarningamber1100: "#433017",
  colorPrimitiveWarningamber1200: "#2C2010",
  colorPrimitiveNeutrallight100: "#FDFDFD",
  colorPrimitiveNeutrallight200: "#F6F5E9",
  colorPrimitiveNeutrallight300: "#EEEDEB",
  colorPrimitiveNeutrallight400: "#E5E3DE",
  colorPrimitiveNeutrallight500: "#D7D4CB",
  colorPrimitiveNeutrallight600: "#C9C4B7",
  colorPrimitiveNeutrallight700: "#B5AFA1",
  colorPrimitiveNeutrallight800: "#9E988A",
  colorPrimitiveNeutrallight900: "#888273",
  colorPrimitiveNeutrallight1000: "#716C5E",
  colorPrimitiveNeutrallight1100: "#555144",
  colorPrimitiveNeutrallight1200: "#3A372F",
  colorPrimitiveNeutraldark100: "#F4F2EF",
  colorPrimitiveNeutraldark200: "#E7E3DE",
  colorPrimitiveNeutraldark300: "#D5CEC5",
  colorPrimitiveNeutraldark400: "#BFB5AA",
  colorPrimitiveNeutraldark500: "#A49688",
  colorPrimitiveNeutraldark600: "#8B7B6D",
  colorPrimitiveNeutraldark700: "#706154",
  colorPrimitiveNeutraldark800: "#564A3F",
  colorPrimitiveNeutraldark900: "#333333",
  colorPrimitiveNeutraldark1000: "#242424",
  colorPrimitiveNeutraldark1100: "#1B1A18",
  colorPrimitiveNeutraldark1200: "#12110F",
  colorPrimitiveCream100: "#FFFEEA",
  colorPrimitiveCream200: "#FEFDDC",
  colorPrimitiveCream300: "#FCFCD4",
  colorPrimitiveCream400: "#F3F2C2",
  colorPrimitiveCream500: "#E6E2A8",
  colorPrimitiveCream600: "#D4CC8A",
  colorPrimitiveCream700: "#B7AF6E",
  colorPrimitiveCream800: "#989152",
  colorPrimitiveCream900: "#79733E",
  colorPrimitiveCream1000: "#5D5A2F",
  colorPrimitiveCream1100: "#413F21",
  colorPrimitiveCream1200: "#2A2916",

  // Color — Semantic
  colorSemanticPrimaryDefault: "#E54633",
  colorSemanticPrimaryHover: "#C53A2B",
  colorSemanticPrimarySoft: "#FFE5DE",
  colorSemanticSecondaryDefault: "#8CC8DB",
  colorSemanticSecondaryHover: "#5799AE",
  colorSemanticSecondarySoft: "#E3F3F8",
  colorSemanticTertiaryDefault: "#5D8DF7",
  colorSemanticTertiaryHover: "#4C79D8",
  colorSemanticTertiarySoft: "#CDD2EB",
  colorSemanticInformationDefault: "#8F99C2",
  colorSemanticInformationStrong: "#4C79D8",
  colorSemanticInformationSoft: "#EFF2FB",
  colorSemanticSuccessDefault: "#6D8E60",
  colorSemanticSuccessStrong: "#43583A",
  colorSemanticSuccessSoft: "#F3F8F2",
  colorSemanticWarningDefault: "#BE8C40",
  colorSemanticWarningStrong: "#7D5A29",
  colorSemanticWarningSoft: "#FFF8EC",
  colorSemanticErrorDefault: "#E54633",
  colorSemanticErrorStrong: "#A83023",
  colorSemanticErrorSoft: "#FFF4F1",
  colorSemanticNeutrallightSurface: "#FDFDFD",
  colorSemanticNeutrallightSurfacealt: "#F6F5E9",
  colorSemanticNeutrallightSurfacesubtle: "#EEEDEB",
  colorSemanticNeutrallightBorder: "#D7D4CB",
  colorSemanticNeutrallightCream: "#FCFCD4",
  colorSemanticNeutraldarkText: "#242424",
  colorSemanticNeutraldarkTextmuted: "#333333",
  colorSemanticNeutraldarkSurface: "#1B1A18",
  colorSemanticNeutraldarkBorder: "#706154",
  colorSemanticNeutraldarkTextstrongaa: "#12110F",
  colorSemanticFoundationsWhite: "#FDFDFD",
  colorSemanticFoundationsBlack: "#242424",

  // Color — Surface
  colorSurfaceLightPage: "#F6F5E9",
  colorSurfaceLightDefault: "#FDFDFD",
  colorSurfaceLightElevated: "#FDFDFD",
  colorSurfaceLightAction: "#E54633",
  colorSurfaceLightActionhover: "#C53A2B",
  colorSurfaceLightActionhoverlight: "#FFE5DE",
  colorSurfaceLightSecondary: "#8CC8DB",
  colorSurfaceLightSecondaryhover: "#5799AE",
  colorSurfaceLightDisabled: "#EEEDEB",
  colorSurfaceLightSuccess: "#F3F8F2",
  colorSurfaceLightWarning: "#FFF8EC",
  colorSurfaceLightInformation: "#EFF2FB",
  colorSurfaceLightError: "#FFF4F1",
  colorSurfaceDarkPage: "#1B1A18",
  colorSurfaceDarkDefault: "#242424",
  colorSurfaceDarkElevated: "#333333",
  colorSurfaceDarkAction: "#E54633",
  colorSurfaceDarkActionhover: "#C53A2B",
  colorSurfaceDarkActionhoverlight: "#FFE5DE",
  colorSurfaceDarkSecondary: "#8CC8DB",
  colorSurfaceDarkSecondaryhover: "#5799AE",
  colorSurfaceDarkDisabled: "#706154",
  colorSurfaceDarkSuccess: "#43583A",
  colorSurfaceDarkWarning: "#7D5A29",
  colorSurfaceDarkInformation: "#4C79D8",
  colorSurfaceDarkError: "#A83023",
  colorSurfaceGradientprimaryfixed: "linear-gradient(135deg, {color.semantic.primary.default} 0%, {color.semantic.secondary.default} 100%)",
  colorSurfaceGradientaccentfixed: "linear-gradient(135deg, {color.semantic.tertiary.default} 0%, {color.semantic.secondary.soft} 100%)",

  // Color — Text
  colorTextLightHeading: "#242424",
  colorTextLightHero: "#242424",
  colorTextLightBody: "#333333",
  colorTextLightCaption: "#333333",
  colorTextLightPlaceholder: "#706154",
  colorTextLightAction: "#E54633",
  colorTextLightActionhover: "#C53A2B",
  colorTextLightDisabled: "#706154",
  colorTextLightOnaction: "#FDFDFD",
  colorTextLightOnsecondary: "#242424",
  colorTextLightOnsurfacesuccess: "#43583A",
  colorTextLightOnsurfacewarning: "#7D5A29",
  colorTextLightOnsurfaceinformation: "#4C79D8",
  colorTextLightOnsurfaceerror: "#A83023",
  colorTextLightSuccess: "#6D8E60",
  colorTextLightWarning: "#BE8C40",
  colorTextLightInformation: "#8F99C2",
  colorTextLightError: "#E54633",
  colorTextLightOnactionaa: "#12110F",
  colorTextLightOnsurfacewarningaa: "#FDFDFD",
  colorTextDarkHeading: "#FDFDFD",
  colorTextDarkHero: "#FDFDFD",
  colorTextDarkBody: "#EEEDEB",
  colorTextDarkCaption: "#D7D4CB",
  colorTextDarkPlaceholder: "#D7D4CB",
  colorTextDarkAction: "#E54633",
  colorTextDarkActionhover: "#C53A2B",
  colorTextDarkDisabled: "#706154",
  colorTextDarkOnaction: "#FDFDFD",
  colorTextDarkOnsecondary: "#242424",
  colorTextDarkOnsurfacesuccess: "#FDFDFD",
  colorTextDarkOnsurfacewarning: "#242424",
  colorTextDarkOnsurfaceinformation: "#FDFDFD",
  colorTextDarkOnsurfaceerror: "#FDFDFD",
  colorTextDarkSuccess: "#6D8E60",
  colorTextDarkWarning: "#BE8C40",
  colorTextDarkInformation: "#8F99C2",
  colorTextDarkError: "#E54633",
  colorTextDarkOnactionaa: "#12110F",
  colorTextDarkOnsurfacewarningaa: "#FDFDFD",

  // Color — Icon
  colorIconLightDefault: "#333333",
  colorIconLightAction: "#E54633",
  colorIconLightActionhover: "#C53A2B",
  colorIconLightDisabled: "#706154",
  colorIconLightSuccess: "#6D8E60",
  colorIconLightWarning: "#BE8C40",
  colorIconLightInformation: "#8F99C2",
  colorIconLightError: "#E54633",
  colorIconDarkDefault: "#EEEDEB",
  colorIconDarkAction: "#E54633",
  colorIconDarkActionhover: "#C53A2B",
  colorIconDarkDisabled: "#706154",
  colorIconDarkSuccess: "#6D8E60",
  colorIconDarkWarning: "#BE8C40",
  colorIconDarkInformation: "#8F99C2",
  colorIconDarkError: "#E54633",

  // Color — Stroke
  colorStrokeLightDefault: "#D7D4CB",
  colorStrokeLightAction: "#E54633",
  colorStrokeLightActionhover: "#C53A2B",
  colorStrokeLightFocus: "#5D8DF7",
  colorStrokeLightDisabled: "#EEEDEB",
  colorStrokeLightSubtle: "#F6F5E9",
  colorStrokeLightSuccess: "#6D8E60",
  colorStrokeLightWarning: "#BE8C40",
  colorStrokeLightInformation: "#8F99C2",
  colorStrokeLightError: "#E54633",
  colorStrokeDarkDefault: "#706154",
  colorStrokeDarkAction: "#E54633",
  colorStrokeDarkActionhover: "#C53A2B",
  colorStrokeDarkFocus: "#5D8DF7",
  colorStrokeDarkDisabled: "#333333",
  colorStrokeDarkSubtle: "#1B1A18",
  colorStrokeDarkSuccess: "#6D8E60",
  colorStrokeDarkWarning: "#BE8C40",
  colorStrokeDarkInformation: "#8F99C2",
  colorStrokeDarkError: "#E54633",
  colorStrokeWidthfixedNone: "0px",
  colorStrokeWidthfixedSmall: "1px",
  colorStrokeWidthfixedMedium: "2px",
  colorStrokeWidthfixedLarge: "3px",

  // Typography — Primitive
  typographyPrimitiveFontfamilyDisplay: "Wixmadefor Display Variable",
  typographyPrimitiveFontfamilyBody: "Wixmadefor Text Variable",
  typographyPrimitiveFontfamilyAccent: "Newsreader Variable",
  typographyPrimitiveFontweightLight: "Light",
  typographyPrimitiveFontweightRegular: "Regular",
  typographyPrimitiveFontweightMedium: "Medium",
  typographyPrimitiveFontweightSemibold: "SemiBold",
  typographyPrimitiveFontweightBold: "Bold",
  typographyPrimitiveFontstyleNormal: "normal",
  typographyPrimitiveFontstyleItalic: "italic",

  // Typography — Alias
  typographyAliasDisplay: "Wixmadefor Display Variable",
  typographyAliasBody: "Wixmadefor Text Variable",
  typographyAliasAccent: "Newsreader Variable",

  // Typography — Vars
  typographyVarsFontsizeDesktopHero: "72",
  typographyVarsFontsizeDesktopH1: "60",
  typographyVarsFontsizeDesktopH2: "48",
  typographyVarsFontsizeDesktopH3: "40",
  typographyVarsFontsizeDesktopH4: "32",
  typographyVarsFontsizeDesktopH5: "24",
  typographyVarsFontsizeDesktopH6: "20",
  typographyVarsFontsizeDesktopBodylarge: "20",
  typographyVarsFontsizeDesktopBodymedium: "16",
  typographyVarsFontsizeDesktopBodysmall: "14",
  typographyVarsFontsizeDesktopBodyxsmall: "12",
  typographyVarsFontsizeDesktopCaption: "12",
  typographyVarsFontsizeTabletHero: "64",
  typographyVarsFontsizeTabletH1: "54",
  typographyVarsFontsizeTabletH2: "44",
  typographyVarsFontsizeTabletH3: "36",
  typographyVarsFontsizeTabletH4: "30",
  typographyVarsFontsizeTabletH5: "24",
  typographyVarsFontsizeTabletH6: "20",
  typographyVarsFontsizeTabletBodylarge: "20",
  typographyVarsFontsizeTabletBodymedium: "16",
  typographyVarsFontsizeTabletBodysmall: "14",
  typographyVarsFontsizeTabletBodyxsmall: "12",
  typographyVarsFontsizeTabletCaption: "12",
  typographyVarsFontsizeMobileHero: "56",
  typographyVarsFontsizeMobileH1: "48",
  typographyVarsFontsizeMobileH2: "40",
  typographyVarsFontsizeMobileH3: "32",
  typographyVarsFontsizeMobileH4: "28",
  typographyVarsFontsizeMobileH5: "24",
  typographyVarsFontsizeMobileH6: "20",
  typographyVarsFontsizeMobileBodylarge: "20",
  typographyVarsFontsizeMobileBodymedium: "16",
  typographyVarsFontsizeMobileBodysmall: "14",
  typographyVarsFontsizeMobileBodyxsmall: "12",
  typographyVarsFontsizeMobileCaption: "12",
  typographyVarsLineheightDesktopHero: "84",
  typographyVarsLineheightDesktopH1: "72",
  typographyVarsLineheightDesktopH2: "56",
  typographyVarsLineheightDesktopH3: "48",
  typographyVarsLineheightDesktopH4: "40",
  typographyVarsLineheightDesktopH5: "28",
  typographyVarsLineheightDesktopH6: "24",
  typographyVarsLineheightDesktopBodylarge: "28",
  typographyVarsLineheightDesktopBodymedium: "24",
  typographyVarsLineheightDesktopBodysmall: "20",
  typographyVarsLineheightDesktopBodyxsmall: "16",
  typographyVarsLineheightDesktopCaption: "16",
  typographyVarsLineheightTabletHero: "84",
  typographyVarsLineheightTabletH1: "72",
  typographyVarsLineheightTabletH2: "56",
  typographyVarsLineheightTabletH3: "48",
  typographyVarsLineheightTabletH4: "40",
  typographyVarsLineheightTabletH5: "28",
  typographyVarsLineheightTabletH6: "24",
  typographyVarsLineheightTabletBodylarge: "28",
  typographyVarsLineheightTabletBodymedium: "24",
  typographyVarsLineheightTabletBodysmall: "20",
  typographyVarsLineheightTabletBodyxsmall: "16",
  typographyVarsLineheightTabletCaption: "16",
  typographyVarsLineheightMobileHero: "84",
  typographyVarsLineheightMobileH1: "72",
  typographyVarsLineheightMobileH2: "56",
  typographyVarsLineheightMobileH3: "48",
  typographyVarsLineheightMobileH4: "40",
  typographyVarsLineheightMobileH5: "28",
  typographyVarsLineheightMobileH6: "24",
  typographyVarsLineheightMobileBodylarge: "28",
  typographyVarsLineheightMobileBodymedium: "24",
  typographyVarsLineheightMobileBodysmall: "20",
  typographyVarsLineheightMobileBodyxsmall: "16",
  typographyVarsLineheightMobileCaption: "16",

  // Spacing
  spacingNone: "0px",
  spacing2xs: "2px",
  spacingXs: "4px",
  spacingSm: "8px",
  spacingMd: "12px",
  spacingLg: "16px",
  spacingXl: "20px",
  spacing2xl: "24px",
  spacing3xl: "28px",
  spacing4xl: "40px",
  spacing5xl: "64px",

  // Border
  borderWidthNone: "0px",
  borderWidthSmall: "1px",
  borderWidthMedium: "2px",
  borderWidthLarge: "3px",
  borderRadiusNone: "0px",
  borderRadiusSmall: "8px",
  borderRadiusMedium: "12px",
  borderRadiusLarge: "16px",
  borderRadiusXl: "24px",
  borderRadiusRound: "9999px",

  // Number
  number25: "1",
  number50: "2",
  number100: "4",
  number200: "8",
  number300: "12",
  number400: "16",
  number500: "20",
  number600: "24",
  number700: "28",
  number800: "32",
  number900: "40",
  number1000: "48",
  number1100: "64",
  number1200: "80",

} as const

export type TokenKey = keyof typeof tokens