// ================================================================
// Design System — Tailwind CSS Config
// Generated from design-tokens.json
//
// Usage: import this in tailwind.config.js
// const { tokens } = require("./framer/tailwind-tokens")
// ================================================================

module.exports = {
  theme: {
    extend: {
      colors: {
        "blue-lavender": {
          "100": "var(--color-primitive-blue-lavender-100)",
          "1000": "var(--color-primitive-blue-lavender-1000)",
          "1100": "var(--color-primitive-blue-lavender-1100)",
          "1200": "var(--color-primitive-blue-lavender-1200)",
          "200": "var(--color-primitive-blue-lavender-200)",
          "300": "var(--color-primitive-blue-lavender-300)",
          "400": "var(--color-primitive-blue-lavender-400)",
          "500": "var(--color-primitive-blue-lavender-500)",
          "600": "var(--color-primitive-blue-lavender-600)",
          "700": "var(--color-primitive-blue-lavender-700)",
          "800": "var(--color-primitive-blue-lavender-800)",
          "900": "var(--color-primitive-blue-lavender-900)",
        },
        "cream": {
          "100": "var(--color-primitive-cream-100)",
          "1000": "var(--color-primitive-cream-1000)",
          "1100": "var(--color-primitive-cream-1100)",
          "1200": "var(--color-primitive-cream-1200)",
          "200": "var(--color-primitive-cream-200)",
          "300": "var(--color-primitive-cream-300)",
          "400": "var(--color-primitive-cream-400)",
          "500": "var(--color-primitive-cream-500)",
          "600": "var(--color-primitive-cream-600)",
          "700": "var(--color-primitive-cream-700)",
          "800": "var(--color-primitive-cream-800)",
          "900": "var(--color-primitive-cream-900)",
        },
        "dark": {
          "action": "var(--color-stroke-dark-action)",
          "action-hover": "var(--color-stroke-dark-action-hover)",
          "action-hover-light": "var(--color-surface-dark-action-hover-light)",
          "body": "var(--color-text-dark-body)",
          "caption": "var(--color-text-dark-caption)",
          "default": "var(--color-stroke-dark-default)",
          "disabled": "var(--color-stroke-dark-disabled)",
          "elevated": "var(--color-surface-dark-elevated)",
          "error": "var(--color-stroke-dark-error)",
          "focus": "var(--color-stroke-dark-focus)",
          "heading": "var(--color-text-dark-heading)",
          "hero": "var(--color-text-dark-hero)",
          "information": "var(--color-stroke-dark-information)",
          "on-action": "var(--color-text-dark-on-action)",
          "on-action-aa": "var(--color-text-dark-on-action-aa)",
          "on-secondary": "var(--color-text-dark-on-secondary)",
          "on-surface-error": "var(--color-text-dark-on-surface-error)",
          "on-surface-information": "var(--color-text-dark-on-surface-information)",
          "on-surface-success": "var(--color-text-dark-on-surface-success)",
          "on-surface-warning": "var(--color-text-dark-on-surface-warning)",
          "on-surface-warning-aa": "var(--color-text-dark-on-surface-warning-aa)",
          "page": "var(--color-surface-dark-page)",
          "placeholder": "var(--color-text-dark-placeholder)",
          "secondary": "var(--color-surface-dark-secondary)",
          "secondary-hover": "var(--color-surface-dark-secondary-hover)",
          "subtle": "var(--color-stroke-dark-subtle)",
          "success": "var(--color-stroke-dark-success)",
          "warning": "var(--color-stroke-dark-warning)",
        },
        "error": {
          "default": "var(--color-semantic-error-default)",
          "soft": "var(--color-semantic-error-soft)",
          "strong": "var(--color-semantic-error-strong)",
        },
        "foundations": {
          "black": "var(--color-semantic-foundations-black)",
          "white": "var(--color-semantic-foundations-white)",
        },
        "information": {
          "default": "var(--color-semantic-information-default)",
          "soft": "var(--color-semantic-information-soft)",
          "strong": "var(--color-semantic-information-strong)",
        },
        "light": {
          "action": "var(--color-stroke-light-action)",
          "action-hover": "var(--color-stroke-light-action-hover)",
          "action-hover-light": "var(--color-surface-light-action-hover-light)",
          "body": "var(--color-text-light-body)",
          "caption": "var(--color-text-light-caption)",
          "default": "var(--color-stroke-light-default)",
          "disabled": "var(--color-stroke-light-disabled)",
          "elevated": "var(--color-surface-light-elevated)",
          "error": "var(--color-stroke-light-error)",
          "focus": "var(--color-stroke-light-focus)",
          "heading": "var(--color-text-light-heading)",
          "hero": "var(--color-text-light-hero)",
          "information": "var(--color-stroke-light-information)",
          "on-action": "var(--color-text-light-on-action)",
          "on-action-aa": "var(--color-text-light-on-action-aa)",
          "on-secondary": "var(--color-text-light-on-secondary)",
          "on-surface-error": "var(--color-text-light-on-surface-error)",
          "on-surface-information": "var(--color-text-light-on-surface-information)",
          "on-surface-success": "var(--color-text-light-on-surface-success)",
          "on-surface-warning": "var(--color-text-light-on-surface-warning)",
          "on-surface-warning-aa": "var(--color-text-light-on-surface-warning-aa)",
          "page": "var(--color-surface-light-page)",
          "placeholder": "var(--color-text-light-placeholder)",
          "secondary": "var(--color-surface-light-secondary)",
          "secondary-hover": "var(--color-surface-light-secondary-hover)",
          "subtle": "var(--color-stroke-light-subtle)",
          "success": "var(--color-stroke-light-success)",
          "warning": "var(--color-stroke-light-warning)",
        },
        "neutral-dark": {
          "100": "var(--color-primitive-neutral-dark-100)",
          "1000": "var(--color-primitive-neutral-dark-1000)",
          "1100": "var(--color-primitive-neutral-dark-1100)",
          "1200": "var(--color-primitive-neutral-dark-1200)",
          "200": "var(--color-primitive-neutral-dark-200)",
          "300": "var(--color-primitive-neutral-dark-300)",
          "400": "var(--color-primitive-neutral-dark-400)",
          "500": "var(--color-primitive-neutral-dark-500)",
          "600": "var(--color-primitive-neutral-dark-600)",
          "700": "var(--color-primitive-neutral-dark-700)",
          "800": "var(--color-primitive-neutral-dark-800)",
          "900": "var(--color-primitive-neutral-dark-900)",
          "border": "var(--color-semantic-neutral-dark-border)",
          "surface": "var(--color-semantic-neutral-dark-surface)",
          "text": "var(--color-semantic-neutral-dark-text)",
          "text-muted": "var(--color-semantic-neutral-dark-text-muted)",
          "text-strong-aa": "var(--color-semantic-neutral-dark-text-strong-aa)",
        },
        "neutral-light": {
          "100": "var(--color-primitive-neutral-light-100)",
          "1000": "var(--color-primitive-neutral-light-1000)",
          "1100": "var(--color-primitive-neutral-light-1100)",
          "1200": "var(--color-primitive-neutral-light-1200)",
          "200": "var(--color-primitive-neutral-light-200)",
          "300": "var(--color-primitive-neutral-light-300)",
          "400": "var(--color-primitive-neutral-light-400)",
          "500": "var(--color-primitive-neutral-light-500)",
          "600": "var(--color-primitive-neutral-light-600)",
          "700": "var(--color-primitive-neutral-light-700)",
          "800": "var(--color-primitive-neutral-light-800)",
          "900": "var(--color-primitive-neutral-light-900)",
          "border": "var(--color-semantic-neutral-light-border)",
          "cream": "var(--color-semantic-neutral-light-cream)",
          "surface": "var(--color-semantic-neutral-light-surface)",
          "surface-alt": "var(--color-semantic-neutral-light-surface-alt)",
          "surface-subtle": "var(--color-semantic-neutral-light-surface-subtle)",
        },
        "primary": {
          "default": "var(--color-semantic-primary-default)",
          "hover": "var(--color-semantic-primary-hover)",
          "soft": "var(--color-semantic-primary-soft)",
        },
        "red-coral": {
          "100": "var(--color-primitive-red-coral-100)",
          "1000": "var(--color-primitive-red-coral-1000)",
          "1100": "var(--color-primitive-red-coral-1100)",
          "1200": "var(--color-primitive-red-coral-1200)",
          "200": "var(--color-primitive-red-coral-200)",
          "300": "var(--color-primitive-red-coral-300)",
          "400": "var(--color-primitive-red-coral-400)",
          "500": "var(--color-primitive-red-coral-500)",
          "600": "var(--color-primitive-red-coral-600)",
          "700": "var(--color-primitive-red-coral-700)",
          "800": "var(--color-primitive-red-coral-800)",
          "900": "var(--color-primitive-red-coral-900)",
        },
        "secondary": {
          "default": "var(--color-semantic-secondary-default)",
          "hover": "var(--color-semantic-secondary-hover)",
          "soft": "var(--color-semantic-secondary-soft)",
        },
        "success": {
          "default": "var(--color-semantic-success-default)",
          "soft": "var(--color-semantic-success-soft)",
          "strong": "var(--color-semantic-success-strong)",
        },
        "success-green": {
          "100": "var(--color-primitive-success-green-100)",
          "1000": "var(--color-primitive-success-green-1000)",
          "1100": "var(--color-primitive-success-green-1100)",
          "1200": "var(--color-primitive-success-green-1200)",
          "200": "var(--color-primitive-success-green-200)",
          "300": "var(--color-primitive-success-green-300)",
          "400": "var(--color-primitive-success-green-400)",
          "500": "var(--color-primitive-success-green-500)",
          "600": "var(--color-primitive-success-green-600)",
          "700": "var(--color-primitive-success-green-700)",
          "800": "var(--color-primitive-success-green-800)",
          "900": "var(--color-primitive-success-green-900)",
        },
        "teal": {
          "100": "var(--color-primitive-teal-100)",
          "1000": "var(--color-primitive-teal-1000)",
          "1100": "var(--color-primitive-teal-1100)",
          "1200": "var(--color-primitive-teal-1200)",
          "200": "var(--color-primitive-teal-200)",
          "300": "var(--color-primitive-teal-300)",
          "400": "var(--color-primitive-teal-400)",
          "500": "var(--color-primitive-teal-500)",
          "600": "var(--color-primitive-teal-600)",
          "700": "var(--color-primitive-teal-700)",
          "800": "var(--color-primitive-teal-800)",
          "900": "var(--color-primitive-teal-900)",
        },
        "tertiary": {
          "default": "var(--color-semantic-tertiary-default)",
          "hover": "var(--color-semantic-tertiary-hover)",
          "soft": "var(--color-semantic-tertiary-soft)",
        },
        "warning": {
          "default": "var(--color-semantic-warning-default)",
          "soft": "var(--color-semantic-warning-soft)",
          "strong": "var(--color-semantic-warning-strong)",
        },
        "warning-amber": {
          "100": "var(--color-primitive-warning-amber-100)",
          "1000": "var(--color-primitive-warning-amber-1000)",
          "1100": "var(--color-primitive-warning-amber-1100)",
          "1200": "var(--color-primitive-warning-amber-1200)",
          "200": "var(--color-primitive-warning-amber-200)",
          "300": "var(--color-primitive-warning-amber-300)",
          "400": "var(--color-primitive-warning-amber-400)",
          "500": "var(--color-primitive-warning-amber-500)",
          "600": "var(--color-primitive-warning-amber-600)",
          "700": "var(--color-primitive-warning-amber-700)",
          "800": "var(--color-primitive-warning-amber-800)",
          "900": "var(--color-primitive-warning-amber-900)",
        },
        "white-and-black": {
          "100": "var(--color-primitive-white-and-black-100)",
          "1200": "var(--color-primitive-white-and-black-1200)",
        },
      },
      spacing: {
        "none": "var(--spacing-none)",
        "2xs": "var(--spacing-2xs)",
        "xs": "var(--spacing-xs)",
        "sm": "var(--spacing-sm)",
        "md": "var(--spacing-md)",
        "lg": "var(--spacing-lg)",
        "xl": "var(--spacing-xl)",
        "2xl": "var(--spacing-2xl)",
        "3xl": "var(--spacing-3xl)",
        "4xl": "var(--spacing-4xl)",
        "5xl": "var(--spacing-5xl)",
      },
      borderRadius: {
        "none": "var(--border-radius-none)",
        "small": "var(--border-radius-small)",
        "medium": "var(--border-radius-medium)",
        "large": "var(--border-radius-large)",
        "xl": "var(--border-radius-xl)",
        "round": "var(--border-radius-round)",
      },
    },
  },
}